Auto select previous layer
earthdaily/qgis-plugin pull request #242
Opened 2022-07-10 12:15 UTC by vermeulendivan

Previously the plugin would always go alphabetically, so if more layers has been added or disabled, the previously selected layer would not be selected. 
With this change, when a coverage search is done on a particular layer, and the user then clicks back after the search, the previous layer will again be selected - even if there has been a change to the layers open or disabled in QGIS. If the layer has been disabled or removed from the open layers in QGIS, it will not be selected but work aphabetically again.

2022-07-14 11:54 UTC, Samweli requested changes

2022-07-14 11:54 UTC, Samweli commented on geosys/ui/widgets/geosys_dockwidget.py
> +        self.current_selected_layer = ''
Lets use `None` instead of `''`.

2022-07-14 11:54 UTC, Samweli commented on geosys/ui/widgets/geosys_dockwidget.py
> +            self.current_selected_layer = ''
same as above

2022-07-15 10:58 UTC, vermeulendivan commented
@Samweli Thanks for the feedback! I've applied the suggestion from your side.

2022-07-21 13:18 UTC, Samweli commented
@vermeulendivan for some reasons the PR keeps failing the CI tests!

2022-08-10 09:34 UTC, merged